### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by dlfdltka** [devhotteok/TwitchLink#12]
1.1.1 업데이트 이후 인코딩이 프로그램 스스로 멈춰지면서 동영상 전체 길이보다 짧게 완료됩니다

**Comment by fade-out-0770** [comment]
I have the same problem as this guy. I downloaded the video using a download tracking function, but a video file shorter than the actual video file length was downloaded.
thanks.

나도 이 남자랑 같은 문제가 있어. 다운로드 추적 기능을 사용하여 동영상을 다운로드했는데 실제 동영상 길이보다 짧은 동영상 파일이 다운로드되었습니다.

**Comment by devhotteok** [comment]
To investigate the problem, please provide as much information about the problem.
(video ID, download settings, whether the video was downloaded while streaming or not, cropped range if you cropped the video, resulted file duration)

**Comment by dlfdltka** [comment]
Streamer ID : ghghgigi
download setting: 음소거 해제, 업데이트 추적

스트리밍 중인 비디오를 다운받으면서 방송 종료 및 추가파일 확인 후 인코딩 시작하였으나 5시간 30분 중 3시간 1분만 인코딩 후
인코딩 종료하였음. 비디오 크롭 없음.

다운로드 중 설정 및 경과 보내드립니다



2022년 1월 3일 (월) 오후 8:29, devhotteok ***@***.***>님이 작성:

**Comment by fade-out-0770** [comment]
[video ID]: 1251614208

[download settings]

https://ibb.co/fxZ3D33
https://ibb.co/nmhTVG1

[Result]
https://ibb.co/HpRFMxf 

[whether the video was downloaded while streaming]
Downloaded using "download tracking" While streaming.

[cropped range if you cropped the video, 
resulted file duration)]
I wanted to receive all the parts of the video, so I didn't use the crop function of the video.

Since the video did not disappear after streaming, in theory, all parts of the video should have been downloaded, but the first part of the video, which should have been downloaded normally, was cut off. (The first part of the video that should have been downloaded at the beginning of the process has disappeared.)

* I learned a new fact while organizing the information. In some cases, videos that have already been recorded are not fully downloaded.
There are times when it is downloaded perfectly and times when it is not. The results change every time try it. I don't know why.


If you don't mind, can you give us permission to use the  old version program?I want to use the old version only while you modify the program.


[비디오 ID]: 1251614208

[다운로드 설정]
https://ibb.co/fxZ3D33
https://ibb.co/nmhTVG1

[결과물]
https://ibb.co/HpRFMxf 

[스트리밍 중 동영상 다운로드 여부]
스트리밍 중 "다운로드 추적"을 사용하여 다운로드되었습니다.

[비디오를 잘랐다면]
결과 파일 기간)]
나는 영상의 모든 부분을 받고 싶어서 자르기 기능을 사용하지 않았습니다.

스트리밍 후 영상이 사라진 것이 아니기 때문에 이론적으로는 영상의 모든 부분을 다운로드 받았어야 하는데, 정상적으로 다운받았어야 할 첫 번째 부분은 잘렸다(처음 다운받았어야 할 영상이 사라졌다)는 것이다.

* 정보를 정리하면서 새로운 사실을 알게 되었습니다. 이미 녹화된 영상이 완전히 다운로드되지 않는 경우도 있다.완벽하게 내려받을 때도 있고 그렇지 않을 때도 있다. 매번 시도해 볼 때마다 결과가 바뀝니다. 왜인지 모르겠다.

괜찮으시다면 구버전 프로그램 사용 허가를 주실 수 있나요? 저는 당신이 프로그램을 수정하는 동안에만 이전 버전을 사용하고 싶습니다.

**Comment by dlfdltka** [comment]
As you said, download was complete but encoding was not successful.

I tried to use old version but program showed update message and shut to
choose cancel before updating so I think it's unable to use old version.

2022년 1월 4일 (화) 오전 12:25, fade-out-0770 ***@***.***>님이 작성:

**Comment by devhotteok** [comment]
It could be a temporary problem with the server or a problem with the program itself.
I'm trying to figure out which of the two is the problem.

**Comment by devhotteok** [comment]
Closed with commit 936c8cf238b435206e4b7be73cf52018aff84e75
