### ISSUE TITLE
창을 여러 개 열어 다운로드 할 때 세부 설정 항목이 연동되지 않습니다

### ISSUE THREAD

**Issue by ywj515** [devhotteok/TwitchLink#13]
프로그램을 여러 개 열 때 파일명 규칙, 저장된 채널 등 설정 항목이 초기화된 채로 나옵니다.
업데이트 후에도 모든 설정이 초기화 되어 다시 설정해야하는 번거로움이 있었습니다.

**Comment by fade-out-0770** [comment]
C:\Users\사용자이름\AppData\Roaming\TwitchLink\settings.tl  파일이 설정파일입니다. 본인이 설정후 따로 백업해 놓으시면 편할겁니다.

**Comment by devhotteok** [comment]
This isn't a bug because I didn't add a 'real-time settings sync'.
An update is planned to enable multiple downloads in one window. After this update, I will be setting up only one window to open.
For this reason, there are no plans to add this feature in the future.
Restart the program to share one setting. This is because the settings are saved when the program exits.
