### ISSUE TITLE
Issue with temporary folder capacity

### ISSUE THREAD

**Issue by fade-out-0770** [devhotteok/TwitchLink#159]
제가 쓰는 컴퓨터는 c드라이브의 용량이 118기가 밖에 되지않습니다. 

빈용량은 60기가정도인데 어느날은 갑자기 다운로드가 멈춰서 보니 

파일 하나가 60기가를 먹을 만큼 임시파일용량을 굉장히 많이 쓰면서 다운로드가 정지하는 상황이 발생하는 것을 보았습니다. 

(C:\Users\AppData\Local\Temp 이 폴더를 말씀드리는것입니다.)

임시파일 경로를 지정할수있게 만들어주시거나 혹시 이 이슈를 해결해 주실수 있을까요.

**Comment by devhotteok** [comment]
TwitchLink isn't the only one using space in temporary folders.
Other programs or the operating system also share this space.
Furthermore, TwitchLink saves only log files in the temporary folder, so it doesn't take up too much space.
If you truly believe the issue is with TwitchLink, please specify exactly which file is causing the problem.
