### ISSUE TITLE
Download Aborted Error

### ISSUE THREAD

**Issue by dantelewandoski** [devhotteok/TwitchLink#198]
Hello,
I do appoligze in advance if this is an error that can be easily fixed and didn't realize it combing through the issues pages.  I am currently getting a download aborted error while downloading to my 4TB External HDD.  Randomly videos will start auto cancelling and gives me an unexpected error download aborted next to the green% bar(forgot to take a screenshot before I restarted).  I was trying to look through the log(attached below and when I got to the bottom it says:
![image](https://github.com/devhotteok/TwitchLink/assets/46252049/113ef14c-4a2d-4917-8933-b0eeaac02b0f)

I thank you for your time and patence for making this great program.

~~~~~~
DanteLewandoski


[TwitchLink_Download_2024.03.25_22-49-51#5d9d7a3a-18a6-4d19-a119-ebaab44c4ba3.log](https://github.com/devhotteok/TwitchLink/files/14750465/TwitchLink_Download_2024.03.25_22-49-51.5d9d7a3a-18a6-4d19-a119-ebaab44c4ba3.log)

Google Doc w/ entire log as well https://docs.google.com/document/d/13R8fIxeDw9BR0QZcPs_LZB62t7RiSt4xb9K1YwxjLmw/edit?usp=sharing

**Comment by devhotteok** [comment]
It seems that your computer's storage speed was not able to keep up with the download speed, or there might have been an issue with the FFmpeg used internally by TwitchLink. Additionally, if you were downloading multiple videos to a single hard drive simultaneously, it's possible that the issue could have been caused by the hard drive being overloaded. For external hard drives, it's common for them to have slower write performance, which likely contributes to this issue.
