### ISSUE TITLE
Too much space

### ISSUE THREAD

**Issue by Cazm023** [devhotteok/TwitchLink#210]
I'm having an issue where when I download a vod directly to an external drive, my local hardrive fills up. After closing the app and/or restarting the computer some of this space is recovered but not all of it. Can someone confirm if there is a method to stop this or where these files are located so I can clear them manually?

**Comment by Mishasama** [comment]
Run this: `%Temp%\TwitchLink`
Then clear all in it.

**Comment by devhotteok** [comment]
Since videos are being downloaded, it's natural for them to take up space on your drive. However, if you notice that more space is disappearing than the size of the downloaded videos, or if deleting videos only recovers part of the space, please check the following:

TwitchLink may use temporary files during the download process, but these are cleaned up once the download is complete. Even if an unexpected shutdown occurs and the temporary files aren't cleaned up, running the application again will remove any leftover files. However, in rare cases, if the drive where the temporary files were stored was disconnected or became inaccessible, the files might not be deleted.

To locate these files, enable the "Show hidden files" option in the folder where the downloads were stored. You should be able to see temporary files used by TwitchLink. If there are no hidden files or folders with the name "TwitchLink" in that location, all temporary files have been properly cleaned, and the issue is unrelated to TwitchLink.
