### ISSUE TITLE
windows defender complains about this program

### ISSUE THREAD

**Issue by Wumisk** [devhotteok/TwitchLink#216]
when trying to open the application, a defender window pops up, which says "windows has protected your computer. Microsoft Defender SmartScreen prevented an unrecognized application from running, which could put your computer at risk"
![image](https://github.com/user-attachments/assets/c5dccf6b-d3dc-4977-9ab2-39f57a9e2b48)

**Comment by devhotteok** [comment]
That notification appears because the application isn't digitally signed, meaning it simply can't verify the application's information. In this case, you can click "More details" to reveal the option to run the application.

This is not a virus warning. However, if you're concerned, you can run another antivirus program or download the source code from this GitHub repository and compile it yourself.
