### ISSUE TITLE
Missing segments Error

### ISSUE THREAD

**Issue by YoungBrosh** [devhotteok/TwitchLink#218]
It is an error that does not allow me to download the live broadcasts correctly, I get this message saying that segments have been lost and when the download finishes only 20 seconds of the live broadcast are downloaded. Can you help me?

![21212](https://github.com/user-attachments/assets/03839bd4-5199-4f54-a781-63521d8adea2)
![21212](https://github.com/user-attachments/assets/0c0fc8fb-5f06-403a-b610-394d295b22fb)

**Comment by devhotteok** [comment]
This issue could have several causes. First, it might be a problem with the video itself. Please try downloading a different video. If the same issue occurs with other videos, try lowering the download speed in the settings. It’s possible that your network is being overloaded due to a slower network speed compared to the download speed.

For a more accurate diagnosis, please attach the log file for this download.
