### ISSUE TITLE
Unknown Network Error

### ISSUE THREAD

**Issue by VyzerMusic** [devhotteok/TwitchLink#230]
Whenever I put a channel name intro the search box, it always "A network error has occurred"

I can successfully download a livestream or a vod when I put the vod ID, but I am unable to see Past Broadcasts

I tried disabling my VPN, but it makes no difference

**Comment by VyzerMusic** [comment]
It wouldn't be too much of an issue if I was able to download through a specific start/end time on a livestream

**Comment by devhotteok** [comment]
This issue may occur in countries where VOD and Clip features are unavailable. In such cases, Twitch’s API does not provide valid responses, resulting in this behavior.

**Comment by VyzerMusic** [comment]
I'm in the United States though? I have no issues looking at past broadcasts and creating clips on the website, and I highly doubt that the USA is the problem

**Comment by VyzerMusic** [comment]
Also, this wasn't always a problem, many months ago I would rarely get this problem, but now, it's very rare that I can get it to work

**Comment by devhotteok** [comment]
If that's the case, it does seem like an issue.
However, to determine whether it’s a problem with your network or the program itself, we’ll need more detailed information.
Could you please provide the following details?

1. When a network error occurs, does the channel page load completely with all information displayed?

2. When a network error occurs, does the video/clip page load completely with all information displayed?

3. Does the issue occur only when searching by Channel ID, or does it also happen with URL or other searches?

4. If you search directly by Video/Clip ID, does the issue still occur?

5. Does the network error occur consistently, or only occasionally?

6. After the network error occurs, does refreshing the page make any difference?

7. Are you using a VPN or any other device/software that might affect your network?

8. When accessing Twitch directly through a browser on the same computer and environment, does everything work normally?

9. Are there any other unusual behaviors or detailed scenarios where the issue occurs?

10. What are the names of the channels where the issue is happening?

**Comment by VyzerMusic** [comment]
When a network error occurs, does the channel page load completely with all information displayed?
Everything appears on the "Stream" tab, however sometimes the "A network error has occurred" shows up, but it doesn't affect the "Stream" tab information

When a network error occurs, does the video/clip page load completely with all information displayed?
When I go to the"Video/Clip" tab, it says "A network error has occurred" and the page is blank other than the error

Does the issue occur only when searching by Channel ID, or does it also happen with URL or other searches?
It only happens when using a channel ID, VOD/Clip links work

If you search directly by Video/Clip ID, does the issue still occur?
No error occurs

Does the network error occur consistently, or only occasionally?
90% of the time, even when I try pushing the refresh button several times, but this only started happening a few months ago and my network has had no changes

After the network error occurs, does refreshing the page make any difference?
It does very rarely, I've tried refreshing 20+ times, but still got the error

Are you using a VPN or any other device/software that might affect your network?
Yes I use a VPN, but I've tested this with and without my VPN

When accessing Twitch directly through a browser on the same computer and environment, does everything work normally?
Yes, everything is normal

Are there any other unusual behaviors or detailed scenarios where the issue occurs?
I don't believe so

What are the names of the channels where the issue is happening?
All channels, but one example is "welcome2bishu"

**Comment by devhotteok** [comment]
Thank you for your report and for providing a detailed explanation of the situation.

However, even under the same conditions, I was unable to reproduce the issue in my environment.
Additionally, there haven’t been any similar reports previously, which makes it difficult to identify the exact cause.

One possible explanation could be that your operating system or kernel-level programs are restricting TwitchLink's network access or causing abnormal handling of specific endpoints used to retrieve data.
However, since you mentioned that there’s no other software affecting the network, this might not be the cause.

Another potential reason could be a malfunctioning antivirus program negatively impacting the network connection.
Please check if this might be the case.

You could also try uninstalling and reinstalling the program, as this might resolve any potential issues.

If none of these approaches resolve the issue, unfortunately, it may be challenging to identify the root cause at this time.

**Comment by VyzerMusic** [comment]
Well today I was able to see the broadcast/clips page without problems, which is rare, and I don't have an active Anti-virus, but if it happens again, I'll try reinstalling

**Comment by devhotteok** [comment]
This might be the cause of the issue.

Twitch uses a system called 'Integrity' to prevent malicious activities such as view botting and macro usage.
This system evaluates the reliability of requests to differentiate between legitimate users and bots.

For general tasks like fetching a single video or clip, Twitch returns valid responses regardless of whether the request is flagged as coming from a user or a bot.
However, for certain operations, such as retrieving lists of videos or clips, Twitch may block requests that are flagged as coming from a bot.

The exact algorithm of this system is private.
However, actions such as running view bots or sending many requests within a short period can significantly increase the likelihood of being flagged.
This issue is also more likely to occur when using a VPN or operating in shared network environments, where multiple users might share the same IP address.

If you’re able to fetch individual videos or clips but not lists, this is likely the underlying issue.
